#!/bin/bash

# Source RVM profile and set ruby / gemset
. /etc/profile

# Select gemset
rvm use "1.9.3-p194@heirloom" --create

# Exit with error if any command returns non zero
set -e

# Bundle gems
bundle

# Run spec tests
rake spec
