#!/bin/bash

# Exit with error if any command returns non zero
set -e

# Source RVM profile and set ruby / gemset
. /etc/profile
rvm use "1.9.3-p125@heirloom" --create

# Bundle gems
bundle

# Run spec tests
rspec spec
